chore: updated the main.yml file to avoid npm ci || npm install failures.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,7 @@ jobs:
             ${{ runner.os }}-node-
 
       - name: Install dependencies
-        run: npm ci
+        run: npm ci || (echo "npm ci failed, falling back to npm install" && npm install)
 
       - name: Update dependencies
         run: npm update
